// import Navbar from '@/components/Navbar'
// import { Inter } from 'next/font/google'
// import Footer from '@/components/Footer'
// import Movingbanner from './Movingbanner'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function Layout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {/* <Navbar /> */}
//         {/* <Movingbanner/> */}
//         <div>
//         {children}
//         </div>
//         {/* <Footer /> */}
//       </body>
//     </html>
//   )
// }
